wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1668676326.127362
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.5
      5: 0.13.5
      6: 4.24.0
      8:
      - 5
asset_dir:
  desc: null
  value: asset/
batch_size:
  desc: null
  value: 64
clip_grad:
  desc: null
  value: 10
data_dir:
  desc: null
  value: /opt/ml/input/data/
device:
  desc: null
  value: cuda
drop_out:
  desc: null
  value: 0.2
file_name:
  desc: null
  value: train_data.csv
hidden_dim:
  desc: null
  value: 64
log_steps:
  desc: null
  value: 50
lr:
  desc: null
  value: 0.0001
max_seq_len:
  desc: null
  value: 20
model:
  desc: null
  value: lstm
model_dir:
  desc: null
  value: models/
model_name:
  desc: null
  value: model.pt
n_epochs:
  desc: null
  value: 20
n_heads:
  desc: null
  value: 2
n_layers:
  desc: null
  value: 2
n_questions:
  desc: null
  value: 9455
n_tag:
  desc: null
  value: 913
n_test:
  desc: null
  value: 1538
num_workers:
  desc: null
  value: 1
optimizer:
  desc: null
  value: adam
output_dir:
  desc: null
  value: output/
patience:
  desc: null
  value: 5
scheduler:
  desc: null
  value: plateau
seed:
  desc: null
  value: 42
test_file_name:
  desc: null
  value: test_data.csv
