wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1668843910.178439
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.13.5
      8:
      - 5
alpha:
  desc: null
  value: null
basepath:
  desc: null
  value: /opt/ml/input/data/
build_kwargs:
  desc: null
  value: {}
embedding_dim:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.001
loader_verbose:
  desc: null
  value: true
n_epoch:
  desc: null
  value: 800
num_layers:
  desc: null
  value: 2
output_dir:
  desc: null
  value: ./output/
pred_file:
  desc: null
  value: submission.csv
use_cuda_if_available:
  desc: null
  value: true
user_wandb:
  desc: null
  value: true
wandb_kwargs:
  desc: null
  value:
    project: dkt-gcn
weight:
  desc: null
  value: ./weight/best_model.pt
weight_basepath:
  desc: null
  value: ./weight
